- hosts: localhost
  connection: local
  tasks:
    - name: Creating resource group
      azure_rm_resourcegroup:
        name: "rg-ansible-test"
        location: "northeurope"

    - name: create an account
      azure_rm_storageaccount:
        resource_group: "rg-ansible-test"
        name: petrostor31
        type: Standard_LRS
        tags:
          testing: testing
          delete: on-exit